using System.Numerics;
using Content.Shared._BaroStation.NuclearReactor;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client._BaroStation.NuclearReactor;

[GenerateTypedNameReferences]
public sealed partial class NuclearReactorConsoleWindow : DefaultWindow
{
    public event Action<bool>? ToggleReactor;
    public event Action<float>? SetTemperature;
    public event Action<int>? EjectRod;
    public event Action<int>? SetCoolingLevel;

    private SlotButton[] _slotButtons = new SlotButton[4];
    private NuclearReactorConsoleUiState? _lastState;
    private PanelContainer _overlayPanel = null!;
    private Label _overlayLabel = null!;
    private bool _isTargetTempFocused;

    public NuclearReactorConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        CreateOverlay();

        ToggleButton.OnPressed += _ => ToggleReactor?.Invoke(!(_lastState?.ReactorEnabled ?? false));
        SetTempButton.OnPressed += _ =>
        {
            if (float.TryParse(TargetTempInput.Text, out var temp))
                SetTemperature?.Invoke(temp);
        };
        CoolingDownButton.OnPressed += _ =>
        {
            var newLevel = (_lastState?.CoolingLevel ?? 1) - 1;
            if (newLevel >= 1)
            {
                SetCoolingLevel?.Invoke(newLevel);
                CoolingLevelLabel.Text = newLevel.ToString();
            }
        };
        CoolingUpButton.OnPressed += _ =>
        {
            var newLevel = (_lastState?.CoolingLevel ?? 1) + 1;
            if (newLevel <= 8)
            {
                SetCoolingLevel?.Invoke(newLevel);
                CoolingLevelLabel.Text = newLevel.ToString();
            }
        };

        TargetTempInput.OnFocusEnter += _ => _isTargetTempFocused = true;
        TargetTempInput.OnFocusExit += _ => _isTargetTempFocused = false;

        for (int i = 0; i < 4; i++)
        {
            var btn = new SlotButton(i);
            btn.OnPressed += _ => EjectRod?.Invoke(btn.SlotIndex);
            _slotButtons[i] = btn;
            RodsGrid.AddChild(btn);
        }
    }

    private void CreateOverlay()
    {
        _overlayPanel = new PanelContainer
        {
            Name = "OverlayPanel",
            Visible = false,
            MouseFilter = Control.MouseFilterMode.Ignore
        };

        var styleBox = new StyleBoxFlat
        {
            BackgroundColor = new Color(0, 0, 0, 0.5f)
        };
        _overlayPanel.PanelOverride = styleBox;

        _overlayLabel = new Label
        {
            Text = Loc.GetString("nuclear-reactor-console-not-linked-overlay"),
            FontColorOverride = Color.White,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = Control.MouseFilterMode.Ignore
        };
        _overlayPanel.AddChild(_overlayLabel);

        AddChild(_overlayPanel);
        _overlayPanel.SetPositionLast();

        LayoutContainer.SetAnchorLeft(_overlayPanel, 0);
        LayoutContainer.SetAnchorRight(_overlayPanel, 1);
        LayoutContainer.SetAnchorTop(_overlayPanel, 0);
        LayoutContainer.SetAnchorBottom(_overlayPanel, 1);
        LayoutContainer.SetMarginTop(_overlayPanel, 30);

        LayoutContainer.SetAnchorLeft(_overlayLabel, 0.5f);
        LayoutContainer.SetAnchorRight(_overlayLabel, 0.5f);
        LayoutContainer.SetAnchorTop(_overlayLabel, 0.5f);
        LayoutContainer.SetAnchorBottom(_overlayLabel, 0.5f);
        LayoutContainer.SetGrowHorizontal(_overlayLabel, LayoutContainer.GrowDirection.Both);
        LayoutContainer.SetGrowVertical(_overlayLabel, LayoutContainer.GrowDirection.Both);
    }

    public void UpdateState(NuclearReactorConsoleUiState state)
    {
        var hasLink = state.HasPower && state.HasReactor;

        if (!hasLink)
        {
            MainContent.Visible = false;
            _overlayPanel.Visible = true;
            return;
        }

        MainContent.Visible = true;
        _overlayPanel.Visible = false;
        _lastState = state;

        if (RodsGrid == null || StatusLabel == null ||
                ToggleButton == null || StateLabel == null || OptimalTempLabel == null ||
                TemperatureLabel == null || TemperatureBar == null || TargetTempInput == null ||
                SetTempButton == null || CoolingDownButton == null || CoolingUpButton == null ||
                CoolingLevelLabel == null || PowerLabel == null || IntegrityLabel == null ||
                DepletedWarningLabel == null || WarningLabel == null)
        {
            return;
        }

        var hasControl = state.HasPower && state.HasReactor;

        ToggleButton.Disabled = !hasControl;
        TargetTempInput.Editable = hasControl;
        SetTempButton.Disabled = !hasControl;
        CoolingDownButton.Disabled = !hasControl || state.CoolingLevel <= 1;
        CoolingUpButton.Disabled = !hasControl || state.CoolingLevel >= 8;

        if (!hasControl)
            StatusLabel.Text = !state.HasReactor
                    ? Loc.GetString("nuclear-reactor-console-no-reactor-short")
                    : Loc.GetString("nuclear-reactor-status-inactive");
        else if (state.ReactorEnabled)
            StatusLabel.Text = Loc.GetString("nuclear-reactor-status-active");
        else
            StatusLabel.Text = Loc.GetString("nuclear-reactor-status-inactive");

        ToggleButton.Text = state.ReactorEnabled
                ? Loc.GetString("nuclear-reactor-window-toggle-off")
                : Loc.GetString("nuclear-reactor-window-toggle-on");

        int activeRodCount = 0;
        foreach (var slot in state.RodSlots)
            if (slot.HasItem && !slot.Depleted) activeRodCount++;

        OptimalTempLabel.Text = $"{activeRodCount * 1000f:F0} K";
        DepletedWarningLabel.Visible = state.HasDepletedRod;

        if (activeRodCount == 0)
        {
            StateLabel.Text = Loc.GetString("nuclear-reactor-mode-no-rods");
            StateLabel.SetOnlyStyleClass("LabelSecondaryColor");
        }
        else
        {
            float optimalMin = state.OptimalTemperature - 300f;
            float optimalMax = state.OptimalTemperature + 300f;

            if (state.CurrentTemperature < optimalMin)
            {
                StateLabel.Text = Loc.GetString("nuclear-reactor-mode-insufficient", ("min", optimalMin));
                StateLabel.SetOnlyStyleClass("LabelCaution");
            }
            else if (state.CurrentTemperature > optimalMax)
            {
                StateLabel.Text = Loc.GetString("nuclear-reactor-mode-excessive", ("max", optimalMax));
                StateLabel.SetOnlyStyleClass("LabelDanger");
            }
            else
            {
                StateLabel.Text = Loc.GetString("nuclear-reactor-mode-optimal", ("min", optimalMin), ("max", optimalMax));
                StateLabel.SetOnlyStyleClass("LabelGood");
            }
        }

        TemperatureLabel.Text = $"{state.CurrentTemperature:F1} K";
        TemperatureBar.Value = state.CurrentTemperature;

        if (!_isTargetTempFocused)
        {
            TargetTempInput.Text = state.TargetTemperature.ToString("F0");
        }

        CoolingLevelLabel.Text = state.CoolingLevel.ToString();
        PowerLabel.Text = $"{state.PowerOutput / 1000f:F1} kW";

        IntegrityLabel.Text = $"{state.Integrity:F0}%";
        if (state.Integrity < 30)
            IntegrityLabel.SetOnlyStyleClass("LabelDanger");
        else if (state.Integrity < 60)
            IntegrityLabel.SetOnlyStyleClass("LabelCaution");
        else
            IntegrityLabel.SetOnlyStyleClass("LabelGood");

        for (int i = 0; i < 4; i++)
        {
            if (i < state.RodSlots.Length)
                _slotButtons[i].UpdateState(state.RodSlots[i]);
        }

        WarningLabel.Visible = activeRodCount == 0;
    }

    private sealed class SlotButton : Button
    {
        public int SlotIndex { get; }
        private readonly Label _textLabel;
        private readonly ProgressBar _fuelBar;

        public SlotButton(int index)
        {
            SlotIndex = index;
            MinSize = new Vector2(100, 80);

            var vbox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };

            _textLabel = new Label { Text = "Empty", HorizontalAlignment = HAlignment.Center };
            _fuelBar = new ProgressBar
            {
                MinSize = new Vector2(80, 10),
                Visible = false,
                MinValue = 0,
                MaxValue = 1,
                Value = 0
            };

            vbox.AddChild(_textLabel);
            vbox.AddChild(_fuelBar);
            AddChild(vbox);
        }

        public void UpdateState(ContainerInfo info)
        {
            if (info.HasItem)
            {
                if (info.Depleted)
                {
                    _textLabel.Text = info.ItemName ?? Loc.GetString("nuclear-reactor-rod");
                    _textLabel.FontColorOverride = Color.Red;
                    _fuelBar.Visible = true;
                    _fuelBar.Value = 0;
                    _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Gray };
                    Disabled = false;
                }
                else
                {
                    _textLabel.Text = info.ItemName ?? Loc.GetString("nuclear-reactor-rod");
                    _textLabel.FontColorOverride = Color.White;

                    if (info.FuelLeft.HasValue)
                    {
                        _fuelBar.Visible = true;
                        _fuelBar.Value = info.FuelLeft.Value;

                        if (info.FuelLeft.Value < 0.2f)
                            _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Red };
                        else if (info.FuelLeft.Value < 0.5f)
                            _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Orange };
                        else
                            _fuelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.LimeGreen };

                        Disabled = false;
                    }
                    else
                    {
                        _fuelBar.Visible = false;
                        Disabled = false;
                    }
                }
            }
            else
            {
                var line1 = Loc.GetString("nuclear-reactor-slot-empty-line1", ("slot", SlotIndex + 1));
                var line2 = Loc.GetString("nuclear-reactor-slot-empty-line2");
                _textLabel.Text = $"{line1}\n{line2}";
                _textLabel.FontColorOverride = Color.White;
                _fuelBar.Visible = false;
                Disabled = true;
            }
        }
    }
}
