using Content.Shared._BaroStation.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._BaroStation.Achievements;

[GenerateTypedNameReferences]
public sealed partial class AchievementEntryControl : BoxContainer
{
    public string AchievementId { get; private set; } = string.Empty;
    public bool IsEarned { get; private set; }

    public AchievementEntryControl(AchievementPrototype prototype, bool isEarned)
    {
        RobustXamlLoader.Load(this);

        AchievementId = prototype.ID;
        IsEarned = isEarned;

        TitleLabel.Text = Loc.GetString(prototype.Name);
        DescriptionLabel.Text = Loc.GetString(prototype.Description);

        if (isEarned)
        {
            Modulate = new Color(200, 200, 200);
            StatusLabel.Text = Loc.GetString("achievements-earned-label");
            AddStyleClass("AchievementEarned");
        }
        else
        {
            Modulate = new Color(100, 100, 100, 180);
            StatusLabel.Text = Loc.GetString("achievements-not-earned-label");
            AddStyleClass("AchievementLocked");
        }
    }
}
