using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._BaroStation.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._BaroStation.Achievements;

[GenerateTypedNameReferences]
public sealed partial class AchievementsWindow : FancyWindow
{
    private List<AchievementPrototype> _cachedAllAchievements = new();
    private HashSet<string> _cachedEarnedIds = new();
    private bool _hasCachedData;

    public AchievementsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public bool IsDisposed => Disposed;

    public void CacheAchievements(List<AchievementPrototype> allAchievements, HashSet<string> earnedIds)
    {
        _cachedAllAchievements = allAchievements;
        _cachedEarnedIds = earnedIds;
        _hasCachedData = true;

        if (IsOpen)
        {
            UpdateAchievements(_cachedAllAchievements, _cachedEarnedIds);
        }
    }

    public void ClearAchievements()
    {
        _hasCachedData = false;
        _cachedEarnedIds.Clear();
        _cachedAllAchievements.Clear();
        ClearList(EarnedList);
        ClearList(LockedList);
        StatsLabel.Text = "Loading achievements...";
    }

    public void UpdateAchievements(List<AchievementPrototype> allAchievements, HashSet<string> earnedIds)
    {
        ClearList(EarnedList);
        ClearList(LockedList);

        if (allAchievements.Count == 0)
        {
            StatsLabel.Text = "No achievements found";
            return;
        }

        var earnedCount = earnedIds.Count;
        StatsLabel.Text = $"Achievements: {earnedCount} / {allAchievements.Count}";

        var earnedAchievements = new List<AchievementPrototype>();
        var lockedAchievements = new List<AchievementPrototype>();

        foreach (var proto in allAchievements)
        {
            if (earnedIds.Contains(proto.ID))
                earnedAchievements.Add(proto);
            else
                lockedAchievements.Add(proto);
        }

        EarnedHeader.Visible = earnedAchievements.Any();
        LockedHeader.Visible = lockedAchievements.Any();
        Separator.Visible = earnedAchievements.Any() && lockedAchievements.Any();

        foreach (var proto in earnedAchievements)
        {
            var entry = new AchievementEntryControl(proto, true);
            EarnedList.AddChild(entry);
        }
        foreach (var proto in lockedAchievements)
        {
            var entry = new AchievementEntryControl(proto, false);
            LockedList.AddChild(entry);
        }
    }

    protected override void Opened()
    {
        base.Opened();

        if (_hasCachedData)
        {
            UpdateAchievements(_cachedAllAchievements, _cachedEarnedIds);
        }
        else
        {
            StatsLabel.Text = "Loading achievements...";

            var entityManager = IoCManager.Resolve<IEntityManager>();
            entityManager.EventBus.RaiseEvent(EventSource.Network, new RequestAchievementsMessage());
        }
    }

    private void ClearList(BoxContainer list)
    {
        var children = list.Children.ToList();
        foreach (var child in children)
        {
            list.RemoveChild(child);
            child.Dispose();
        }
    }
}
