using Content.Shared._BaroStation.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Timing;

namespace Content.Client._BaroStation.Achievements;

[GenerateTypedNameReferences]
public sealed partial class ToastNotification : PanelContainer
{

    private AchievementPrototype _prototype;
    private float _lifeTime;
    private bool _isClosing;
    private bool _isShown;

    public event Action? OnClosed;

    public ToastNotification(AchievementPrototype prototype)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _prototype = prototype;

        AchievementNameLabel.Text = Loc.GetString(_prototype.Name);
        TitleLabel.Text = Loc.GetString("achievements-toast-title");

        Modulate = new Color(1, 1, 1, 0);
        Visible = true;
    }

    public void Show()
    {
        if (_isShown)
            return;

        _isShown = true;
        _lifeTime = 0;
        _isClosing = false;

        if (Parent == null && UserInterfaceManager.PopupRoot != null)
        {
            UserInterfaceManager.PopupRoot.AddChild(this);

            LayoutContainer.SetAnchorBottom(this, 1);
            LayoutContainer.SetAnchorRight(this, 1);
            LayoutContainer.SetMarginBottom(this, 10);
            LayoutContainer.SetMarginRight(this, 10);
        }
    }

    public void Close()
    {
        if (_isClosing)
            return;

        _isClosing = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!Visible || !_isShown)
            return;

        _lifeTime += args.DeltaSeconds;

        if (_lifeTime < 0.2f && !_isClosing)
        {
            var progress = _lifeTime / 0.2f;
            Modulate = new Color(1, 1, 1, progress);
        }
        else if (_lifeTime > 4.8f || _isClosing)
        {
            var closeProgress = _isClosing ? Math.Min(1f, (_lifeTime - 4.5f) / 0.3f) : (_lifeTime - 4.8f) / 0.2f;
            if (closeProgress >= 1f)
            {
                Visible = false;
                _isShown = false;
                UserInterfaceManager.DeferAction(() =>
                {
                    if (Parent != null && !Disposed)
                    {
                        Orphan();
                    }
                    OnClosed?.Invoke();
                });
                return;
            }
            Modulate = new Color(1, 1, 1, 1 - closeProgress);
        }
        else if (_lifeTime > 5f && !_isClosing)
        {
            Close();
        }
    }
}
